language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t rodobkn/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rodobkn/react-test npm test

after_success:
  - docker build -t rodobkn/multi-client ./client
  - docker build -t rodobkn/multi-nginx ./nginx
  - docker build -t rodobkn/multi-server ./server
  - docker build -t rodobkn/multi-worker ./worker
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push rodobkn/multi-client
  - docker push rodobkn/multi-nginx
  - docker push rodobkn/multi-server
  - docker push rodobkn/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-114047053983'
  bucket_path: 'multi-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
